image: docker:20.10

variables:
  DOCKER_REGISTRY: 986249049395.dkr.ecr.ap-northeast-2.amazonaws.com
  APP_NAME: soona

stages:
  - build
  - test
  - package
  - publish
  - deploy

build:
  image: gradle:alpine
  # gradle 버전 확인 필요
  stage: build
  script:
    - echo "gradle build"
    - chmod +x gradlew
    - ./gradlew clean
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - master

test:
  # image jdk
  stage: test
  script:
    - echo "pass"
    # - ./gradlew test
  only:
    - master
  # 일단 생략


package:
  stage: package
  image:
    name: docker:stable
  services:
    - name: docker:dind
      alias: dockerdaemon
  variables:
    # Tell docker CLI how to talk to Docker daemon.
    DOCKER_HOST: tcp://dockerdaemon:2375/
    # Use the overlayfs driver for improved performance.
    DOCKER_DRIVER: overlay2
    # Disable TLS since we're running inside local network.
    DOCKER_TLS_CERTDIR: ""
  script:
    # GitLab has a built-in Docker image registry, whose
    # parameters are set automatically. You can use some
    # other Docker registry though by changing the login and
    # image name.
    #- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    #- docker build -t "$CI_REGISTRY_IMAGE:latest" .
    #- docker push "$CI_REGISTRY_IMAGE:latest"
    #- docker logout
    - docker build -t soona:latest .
  artifacts:
    paths:
      - /var/lib/docker/overlay2
    expire_in: 1 day
  only:
    - master

publish:
  # upload to ecr
  stage: publish
  before_script:
    - ntpd -q -p time.nist.gov
    - apk add --no-cache curl jq python3 py-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws --version
    - docker info
    - docker --version
  script:
    - docker tag soona:latest $DOCKER_REGISTRY/$APP_NAME:latest
    - docker push $DOCKER_REGISTRY/$APP_NAME:latest
  only:
    - master
