image: docker:20.10

variables:
  DOCKER_REGISTRY: 986249049395.dkr.ecr.ap-northeast-2.amazonaws.com
  APP_NAME: soona

stages:
  - build
  - test
  - package
  - deploy

build:
  image: gradle:alpine
  # gradle 버전 확인 필요
  stage: build
  script:
    - echo "gradle build"
    - chmod +x gradlew
    - ./gradlew clean
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - master

test:
  # image: gradle:alpine
  stage: test
  script:
    - ./gradlew test
    #- echo "파이프라인너무오래걸려서테스트생략"
  only:
    - master

package:
  stage: package
  image:
    name: docker:stable
  services:
    - name: docker:dind
      alias: dockerdaemon
  variables:
    # Tell docker CLI how to talk to Docker daemon.
    DOCKER_HOST: tcp://dockerdaemon:2375/
    # Use the overlayfs driver for improved performance.
    DOCKER_DRIVER: overlay2
    # Disable TLS since we're running inside local network.
    DOCKER_TLS_CERTDIR: ""
  script:
    # GitLab has a built-in Docker image registry, whose
    # parameters are set automatically. You can use some
    # other Docker registry though by changing the login and
    # image name.
    - docker build -t soona:latest .
    # now upload to ecr
    - ntpd -q -p time.nist.gov
    - apk add --no-cache curl jq python3 py-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws --version
    - docker info
    - docker --version
    - docker tag soona:latest $DOCKER_REGISTRY/$APP_NAME:latest
    - docker push $DOCKER_REGISTRY/$APP_NAME:latest
  only:
    - master

deploy:
  stage: deploy
  image:
    name: docker:stable
  services:
    - name: docker:dind
      alias: dockerdaemon
  variables:
    TASK_DEF_NAME: soona-backend-task
    CLUSTER_NAME: soona-cluster
    SERVICE_NAME: soona-backend-task-service
    DOCKER_HOST: tcp://dockerdaemon:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "deploy start"
    - ntpd -q -p time.nist.gov
    - apk add --no-cache curl jq python3 py-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    #- filePath="/bin/LEAP/$TASK_DEF_NAME.json"
    #- export task_version=$(aws ecs describe-task-definition --cli-input-json file://$filePath --region $region | jq --raw-output '.taskDefinition.revision') --debug
    #- aws ecs register-task-definition --cli-input-json $filePath.sjon --region $AWS_REGION --debug
    #- aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $TASK_DEF_NAME --region $AWS_REGION 
    - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
