image: docker:20.10

variables:
  DOCKER_REGISTRY: 986249049395.dkr.ecr.ap-northeast-2.amazonaws.com
  APP_NAME: soona
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - publish
  - deploy

build:
  image: gradle:alpine
  # gradle 버전 확인 
  stage: build
  services:
    - docker:dind
  script:
    - echo "gradle build"
    - chmod +x gradlew
    - echo "gradle build start---"
    - ./gradlew clean
    - ./gradlew build
    - apk add --no-cache bash python3
    - echo "docker build start---"
    - docker build -t soona:latest .
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - master
    
test:
  stage: test
  script:
    - echo "pass"
  only:
    - master
  # 일단 생략

publish:
  # upload to ecr
  stage: publish
  before_script:
    - ntpd -q -p time.nist.gov
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws --version
    - docker info
    - docker --version
  script:
    - docker tag soona:latest $DOCKER_REGISTRY/$APP_NAME:latest
    - docker push $DOCKER_REGISTRY/$APP_NAME:latest
  only:
    - master
